(()=>{'use strict';
const TYPES={roman_imperial:'Roman Imperial',roman_provincial:'Roman Provincial',byzantine:'Byzantine'},S={coins:[],type:'',q:'',ruler:'',mint:'',denom:'',material:'',sub:'',sort:'date-asc'},D={};
document.addEventListener('DOMContentLoaded',init);
function el(id){return document.getElementById(id)}
async function init(){['stats','collectionTabs','searchInput','filterToggle','activeFilterCount','filtersPanel','rulerFilter','mintFilter','denomFilter','materialFilter','subCollectionFilter','clearFilters','sortSelect','resultCount','randomCoin','coinGrid','emptyState','errorState','coinDialog','dialogContent','dialogClose','aboutButton','aboutDialog','aboutClose'].forEach(k=>D[k]=el(k));wire();readUrl();try{const r=await fetch('coins.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);S.coins=normalize(await r.json());tabs();filters();controls();stats();render();openFromUrl()}catch(e){console.error(e);D.coinGrid.hidden=true;D.resultCount.textContent='Collection unavailable';D.errorState.hidden=false}}
function wire(){D.searchInput.addEventListener('input',()=>{S.q=D.searchInput.value.trim();render()});[[D.rulerFilter,'ruler'],[D.mintFilter,'mint'],[D.denomFilter,'denom'],[D.materialFilter,'material'],[D.subCollectionFilter,'sub']].forEach(([x,k])=>x.addEventListener('change',()=>{S[k]=x.value;render()}));D.sortSelect.addEventListener('change',()=>{S.sort=D.sortSelect.value;render()});D.filterToggle.addEventListener('click',()=>{const o=D.filtersPanel.hidden;D.filtersPanel.hidden=!o;D.filterToggle.setAttribute('aria-expanded',String(o))});D.clearFilters.addEventListener('click',clear);D.randomCoin.addEventListener('click',random);D.dialogClose.addEventListener('click',closeCoin);D.coinDialog.addEventListener('click',backdrop);D.aboutButton.addEventListener('click',()=>D.aboutDialog.showModal());D.aboutClose.addEventListener('click',()=>D.aboutDialog.close());D.aboutDialog.addEventListener('click',backdrop);window.addEventListener('popstate',()=>{readUrl();controls();render();openFromUrl()})}
function normalize(data){const out=[];(Array.isArray(data)?data:[]).forEach(sec=>Object.entries(sec||{}).forEach(([type,arr])=>(Array.isArray(arr)?arr:[]).forEach(w=>Object.values(w||{}).forEach(c=>{if(c&&typeof c==='object'&&c.file)out.push({...c,_type:type})}))));return out.map((c,i)=>({...c,_id:c.file||`coin-${i}`,_label:TYPES[c._type]||title(String(c._type||'Collection').replaceAll('_',' ')),_subs:Array.isArray(c.sub_collection)?c.sub_collection:[]}))}
function tabs(){const counts={};S.coins.forEach(c=>counts[c._type]=(counts[c._type]||0)+1);D.collectionTabs.replaceChildren(tab('','All coins',S.coins.length),...Object.entries(TYPES).filter(([k])=>counts[k]).map(([k,v])=>tab(k,v,counts[k])))}
function tab(v,l,n){const b=document.createElement('button');b.type='button';b.className='collection-tab';b.dataset.type=v;b.innerHTML=`${esc(l)} <span class="count">${n}</span>`;b.addEventListener('click',()=>{S.type=v;render()});return b}
function filters(){fill(D.rulerFilter,S.coins.map(c=>c.emperor),'All rulers');fill(D.mintFilter,S.coins.map(c=>c.mint),'All mints');fill(D.denomFilter,S.coins.map(c=>c.denomination),'All denominations');fill(D.materialFilter,S.coins.map(c=>c.material),'All materials');fill(D.subCollectionFilter,S.coins.flatMap(c=>c._subs),'All sub-collections')}
function fill(sel,vals,label){sel.replaceChildren(new Option(label,''),...unique(vals).map(v=>new Option(v,v)))}
function stats(){const years=S.coins.flatMap(c=>[Number(c.yearl),Number(c.yearh)]).filter(Number.isFinite),mints=new Set(S.coins.map(c=>c.mint).filter(Boolean));let span='—';if(years.length){const lo=Math.min(...years),hi=Math.max(...years);span=hi-lo+1-(lo<0&&hi>0?1:0)}D.stats.innerHTML=`<div><strong>${S.coins.length}</strong><span>coins</span></div><div><strong>${mints.size}</strong><span>mints</span></div><div><strong>${span}</strong><span>years represented</span></div>`}
function filtered(){const q=S.q.toLowerCase();let a=S.coins.filter(c=>(!S.type||c._type===S.type)&&(!S.ruler||c.emperor===S.ruler)&&(!S.mint||c.mint===S.mint)&&(!S.denom||c.denomination===S.denom)&&(!S.material||c.material===S.material)&&(!S.sub||c._subs.includes(S.sub))&&(!q||search(c).includes(q)));const txt=k=>(x,y)=>String(x[k]||'').localeCompare(String(y[k]||''),undefined,{sensitivity:'base'});const sort={ 'date-desc':(a,b)=>num(b.yearl,-Infinity)-num(a.yearl,-Infinity),'ruler-asc':txt('emperor'),'mint-asc':txt('mint'),'denom-asc':txt('denomination'),'date-asc':(a,b)=>num(a.yearl,Infinity)-num(b.yearl,Infinity)}[S.sort]||((a,b)=>num(a.yearl,Infinity)-num(b.yearl,Infinity));return a.sort(sort)}
function search(c){return [c.emperor,c.material,c.denomination,c.mint,c.officina,c.reference,c.obverse_legend,c.reverse_legend,c.exergue,c.obverse_desc,c.reverse_desc,c.provenance,c.code,c._label,...c._subs].filter(Boolean).join(' ').toLowerCase()}
function render(){const a=filtered();D.coinGrid.replaceChildren(...a.map(card));D.coinGrid.hidden=!a.length;D.emptyState.hidden=!!a.length;D.errorState.hidden=true;D.coinGrid.setAttribute('aria-busy','false');D.resultCount.textContent=`${a.length} ${a.length===1?'coin':'coins'} shown`;D.collectionTabs.querySelectorAll('.collection-tab').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.type===S.type)));const n=[S.type,S.ruler,S.mint,S.denom,S.material,S.sub].filter(Boolean).length;D.activeFilterCount.textContent=n;D.activeFilterCount.hidden=!n;updateUrl()}
function card(c){const a=document.createElement('article');a.className='coin-card';const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`View ${c.emperor||'coin'} ${c.denomination||''}`.trim());b.innerHTML=`<div class="coin-image-wrap"><img src="${attr(image(c))}" alt="${attr(alt(c))}" loading="lazy" decoding="async"><span class="coin-badge">${esc(c._label)}</span></div><div class="coin-card-copy"><h2>${esc(c.emperor||'Unattributed')}</h2><p class="coin-subtitle">${esc([c.material,c.denomination,date(c)].filter(Boolean).join(' · '))}</p><div class="coin-meta"><span>${esc(c.mint?`${c.mint} mint`:'Mint not recorded')}</span><span class="reference">${esc(c.reference||'')}</span></div></div>`;b.addEventListener('click',()=>openCoin(c));a.appendChild(b);return a}
function openCoin(c,push=true){D.dialogContent.innerHTML=detail(c);if(!D.coinDialog.open)D.coinDialog.showModal();if(push){const u=new URL(location.href);u.searchParams.set('coin',c._id);history.pushState({},'',u)}}
function closeCoin(){if(D.coinDialog.open)D.coinDialog.close();const u=new URL(location.href);u.searchParams.delete('coin');history.replaceState({},'',u)}
function backdrop(e){if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect(),inside=e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;if(!inside)e.currentTarget===D.coinDialog?closeCoin():e.currentTarget.close()}
function detail(c){const items=[['Date',date(c)],['Mint',c.mint],['Officina',c.officina],['Weight',c.weight!=null?`${c.weight} g`:null],['Diameter',c.diameter],['Axis',c.axis],['Emission',c.emission],['Reference',c.reference],['Record',c.code]].filter(x=>has(x[1])),subs=c._subs.length?`<ul class="subcollection-list">${c._subs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';return `<article class="coin-detail"><div class="detail-image"><img src="${attr(c.image_large||c.image||image(c))}" alt="${attr(alt(c))}"></div><div class="detail-copy"><p class="eyebrow">${esc(c._label)}</p><h2>${esc(c.emperor||'Unattributed')}</h2><p class="detail-lede">${esc([c.material,c.denomination,c.mint?`${c.mint} mint`:null].filter(Boolean).join(' · '))}</p><dl class="catalog-grid">${items.map(([l,v])=>`<div><dt>${esc(l)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${section('Obverse',c.obverse_legend,c.obverse_desc)}${section('Reverse',c.reverse_legend,c.reverse_desc)}${has(c.exergue)?`<section class="detail-section"><h3>Exergue</h3><p class="legend">${esc(c.exergue)}</p></section>`:''}${has(c.provenance)?`<section class="detail-section"><h3>Provenance</h3><p>${esc(c.provenance)}</p>${subs}</section>`:subs?`<section class="detail-section"><h3>Sub-collections</h3>${subs}</section>`:''}</div></article>`}
function section(t,l,d){if(!has(l)&&!has(d))return'';return `<section class="detail-section"><h3>${t}</h3>${has(l)&&l!=='-'?`<p class="legend">${esc(l)}</p>`:''}${has(d)?`<p>${esc(d)}</p>`:''}</section>`}
function random(){const a=filtered();if(a.length)openCoin(a[Math.floor(Math.random()*a.length)])}
function clear(){Object.assign(S,{type:'',q:'',ruler:'',mint:'',denom:'',material:'',sub:''});controls();render()}
function readUrl(){const p=new URLSearchParams(location.search);S.type=p.get('type')||'';S.q=p.get('q')||'';S.ruler=p.get('ruler')||'';S.mint=p.get('mint')||'';S.denom=p.get('denom')||'';S.material=p.get('material')||'';S.sub=p.get('sub')||'';S.sort=p.get('sort')||'date-asc'}
function controls(){D.searchInput.value=S.q;D.rulerFilter.value=S.ruler;D.mintFilter.value=S.mint;D.denomFilter.value=S.denom;D.materialFilter.value=S.material;D.subCollectionFilter.value=S.sub;D.sortSelect.value=S.sort}
function updateUrl(){const u=new URL(location.href),p=u.searchParams;[['type',S.type],['q',S.q],['ruler',S.ruler],['mint',S.mint],['denom',S.denom],['material',S.material],['sub',S.sub],['sort',S.sort==='date-asc'?'':S.sort]].forEach(([k,v])=>v?p.set(k,v):p.delete(k));history.replaceState({},'',u)}
function openFromUrl(){const id=new URLSearchParams(location.search).get('coin'),c=S.coins.find(x=>x._id===id);if(c)openCoin(c,false)}
function image(c){return c.image||`images/${encodeURIComponent(c.file)}/${encodeURIComponent(c.file)}%20(Small).jpg`}
function date(c){const a=Number(c.yearl),b=Number(c.yearh);if(!Number.isFinite(a)&&!Number.isFinite(b))return'';const fmt=y=>`${Math.abs(y)} ${y<0?'BC':'AD'}`;if(!Number.isFinite(b)||a===b)return fmt(a);if(a<0&&b<0)return `${Math.abs(a)}–${Math.abs(b)} BC`;if(a>=0&&b>=0)return `${a}–${b} AD`;return `${fmt(a)}–${fmt(b)}`}
function alt(c){return [c.emperor,c.material,c.denomination,date(c)].filter(Boolean).join(', ')}function unique(v){return [...new Set(v.filter(has).map(String))].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base',numeric:true}))}function num(v,f){v=Number(v);return Number.isFinite(v)?v:f}function has(v){return v!==null&&v!==undefined&&v!==''}function title(v){return v.replace(/\b\w/g,x=>x.toUpperCase())}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function attr(v){return esc(v)}
})();
